solver: main.cpp search.cpp search2.cpp swap.cpp eval.cpp eval2.cpp output.cpp
	g++ -O3 -mtune=native -march=native -mfpmath=both main.cpp search.cpp search2.cpp swap.cpp eval.cpp eval2.cpp output.cpp